### PR TITLE
fix: keycloak SSR & migrate deprecated service

### LINKED ISSUE #293: Keycloak SSR breaks application
# Context
After migrating to standalone it seems that Keycloak is having some issues with SSR (#285). One reason for that is probably that even with our current window checks that the KeycloakService is not automatically guarded against window access during SSR. In my current understanding for the new standalone mode, Angular runs providers earlier, before SSR has established browser guards, but that's just my current assumption. So I guess it's some lifecycle behaviour that breaks the system currently. We should probably also refactor and move to the new `provideKeycloak()` provider instead of our current deprecated approach. 

This also seems to be a known issue https://github.com/mauriciovigolo/keycloak-angular/issues/612.

## Steps to Reproduce
1. Run pnpm build:frontend
2. Run node dist/apps/frontend/server/server.mjs
3. Open localhost

### PR DESCRIPTION
**Pull request by lekhmanrus**
This PR addresses server-side rendering (SSR) compatibility issues related to Keycloak integration and updates deprecated authentication service usage.
The goal is to ensure stable authentication behavior in both SSR and client-side contexts while removing reliance on deprecated APIs.

**Key Changes**
* Fixed SSR-related errors caused by improper use of browser-only APIs in Keycloak initialization.
* Migrated from deprecated `KeycloakService` to the new, supported service interface from `keycloak-js`.
* Updated dependency injection and initialization flow to ensure compatibility with Angular SSR.
* Cleaned up redundant imports and improved type safety in authentication-related modules.
* Adjusted initialization logic to avoid runtime errors when rendering on the server.

close #293

### CODE REVIEW

**Comment by Morphclue** [comment]
I haven’t had a detailed look at the PR yet, but I quickly tested it locally. Running `pnpm build:frontend` followed by
`node dist/apps/frontend/server/server.mjs`
results in:
```ts
ReferenceError: window is not defined
    at file:///C:/Projects/apollusia/dist/apps/frontend/server/chunk-KVMCL7QG.mjs:75:3867
    at ModuleJob.run (node:internal/modules/esm/module_job:327:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:663:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:99:5)
    ```

**Comment by Morphclue** [comment]
After quite some trial and error, I’m still not sure how to properly fix the current issue in this PR and on the master branch.
Here are a few areas that might be worth revisiting. Some of them I might have implemented incorrectly:

* Adjusting proxy.conf.json
* Updating server.ts to include middleware proxies
* Using @defer for certain components

These brought some improvement, but it’s still not working as expected. I might temporarily disable SSR until we have a proper fix, since the website isn’t really usable with the new standalone architecture right now. This one is on me of course, since I've merged it without properly testing SSR. Let's give it another 1-2 days until a final decision for the temporary fix.

**Comment by Morphclue** [comment]
@lekhmanrus Unfortunately it's still hitting similiar errors. Have you tried running it locally and trying to see if it works? I rolled the PROD server back so it's stable for now and on a version that's pre-standalone.

File: apps/frontend/server.ts [hunk 1]
```diff
@@ -1,67 +1,63 @@
...
+      .catch(next);
   });
 
   return server;
 }
 
 function run(): express.Express {
-  const port = process.env['PORT'] || 4000;
-
   // Start up the Node server
```
Comment (Morphclue) [inline apps/frontend/server.ts]:
```suggestion
```

File: apps/frontend/src/app/provide-keycloak-ssr.ts [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+
+  /**
+   * Optional array of additional Angular providers or environment providers.
+   */
+  providers?: Array<Provider | EnvironmentProviders>;
+
+  /**
+   * Optional array of Keycloak features to extend the functionality of the Keycloak integration.
+   */
+  features?: Array<KeycloakFeature>;
```
Comment (Morphclue) [inline apps/frontend/src/app/provide-keycloak-ssr.ts]:
```suggestion
  config: KeycloakConfig;
  initOptions?: KeycloakInitOptions;
  providers?: Array<Provider | EnvironmentProviders>;
  features?: Array<KeycloakFeature>;
```

**Review by Morphclue — CHANGES_REQUESTED** [review]
From my POV we can try it out. As you've mentioned the generated file looks similar to the one `ng new` with SSR creates. Can you clean up the code?
